/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/kaneko_takayuki/.choosenim/toolchains/nim-0.18.0/lib -o /Users/kaneko_takayuki/MyProgram/ReversiAI/src/constants/nimcache/aiConfig.o /Users/kaneko_takayuki/MyProgram/ReversiAI/src/constants/nimcache/aiConfig.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef NI tyArray_SLBTEB08vk46ttuRaTxAYw[64];
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, aiConfigDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
NIM_CONST tyArray_SLBTEB08vk46ttuRaTxAYw VALUE_TABLE_fpAvbcnquW9b558jo1cCeDg = {((NI) 30),
((NI) -12),
((NI) 0),
((NI) -1),
((NI) -1),
((NI) 0),
((NI) -12),
((NI) 30),
((NI) -12),
((NI) -20),
((NI) -3),
((NI) -3),
((NI) -3),
((NI) -3),
((NI) -20),
((NI) -12),
((NI) 0),
((NI) -3),
((NI) 0),
((NI) -1),
((NI) -1),
((NI) 0),
((NI) -3),
((NI) 0),
((NI) -1),
((NI) -3),
((NI) -1),
((NI) -1),
((NI) -1),
((NI) -1),
((NI) -3),
((NI) -1),
((NI) -1),
((NI) -3),
((NI) -1),
((NI) -1),
((NI) -1),
((NI) -1),
((NI) -3),
((NI) -1),
((NI) 0),
((NI) -3),
((NI) 0),
((NI) -1),
((NI) -1),
((NI) 0),
((NI) -3),
((NI) 0),
((NI) -12),
((NI) -20),
((NI) -3),
((NI) -3),
((NI) -3),
((NI) -3),
((NI) -20),
((NI) -12),
((NI) 30),
((NI) -12),
((NI) 0),
((NI) -1),
((NI) -1),
((NI) 0),
((NI) -12),
((NI) 30)}
;

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	aiConfigDatInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}


static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("aiConfig", "aiConfig.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, aiConfigDatInit000)(void) {
}

