/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/kaneko_takayuki/.choosenim/toolchains/nim-0.18.0/lib -o /Users/kaneko_takayuki/MyProgram/ReversiAI/src/nimcache/aiConfig.o /Users/kaneko_takayuki/MyProgram/ReversiAI/src/nimcache/aiConfig.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef NI tyArray_SLBTEB08vk46ttuRaTxAYw[64];
NIM_CONST tyArray_SLBTEB08vk46ttuRaTxAYw VALUE_TABLE_fpAvbcnquW9b558jo1cCeDg = {((NI) 30),
((NI) -12),
((NI) 0),
((NI) -1),
((NI) -1),
((NI) 0),
((NI) -12),
((NI) 30),
((NI) -12),
((NI) -20),
((NI) -3),
((NI) -3),
((NI) -3),
((NI) -3),
((NI) -20),
((NI) -12),
((NI) 0),
((NI) -3),
((NI) 0),
((NI) -1),
((NI) -1),
((NI) 0),
((NI) -3),
((NI) 0),
((NI) -1),
((NI) -3),
((NI) -1),
((NI) -1),
((NI) -1),
((NI) -1),
((NI) -3),
((NI) -1),
((NI) -1),
((NI) -3),
((NI) -1),
((NI) -1),
((NI) -1),
((NI) -1),
((NI) -3),
((NI) -1),
((NI) 0),
((NI) -3),
((NI) 0),
((NI) -1),
((NI) -1),
((NI) 0),
((NI) -3),
((NI) 0),
((NI) -12),
((NI) -20),
((NI) -3),
((NI) -3),
((NI) -3),
((NI) -3),
((NI) -20),
((NI) -12),
((NI) 30),
((NI) -12),
((NI) 0),
((NI) -1),
((NI) -1),
((NI) 0),
((NI) -12),
((NI) 30)}
;
NIM_EXTERNC N_NOINLINE(void, unknown_aiConfigInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, unknown_aiConfigDatInit000)(void) {
}

