/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/kaneko_takayuki/.choosenim/toolchains/nim-0.18.0/lib -o /Users/kaneko_takayuki/MyProgram/ReversiAI/src/nimcache/command_line.o /Users/kaneko_takayuki/MyProgram/ReversiAI/src/nimcache/command_line.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, readLine_fPRnXwDTqtynUYGl4OixAg)(FILE* f);
N_LIB_PRIVATE N_NIMCALL(NI, convert_input_r1IZlm9cBhFRGirXlHo4Wsw)(NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NU64, getPutBoard_zeO1KqsRtyEbP9bosMoaBIw)(NU64 me, NU64 op);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_LIB_PRIVATE N_NIMCALL(void, add_IbYQ9cTcoQ89aIwM2IEYGMng)(NimStringDesc** result, NI64 x);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NI, count_Na1w7t9aRHVrWznkd3g2YGQ)(NU64 x);
STRING_LITERAL(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_3, "\345\205\245\345\212\233: ", 8);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_2 = {((NimStringDesc*) &TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_3)}
;
STRING_LITERAL(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_5, " |A|B|C|D|E|F|G|H|", 18);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_4 = {((NimStringDesc*) &TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_5)}
;
STRING_LITERAL(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_7, "- - - - - - - - - ", 18);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_6 = {((NimStringDesc*) &TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_7)}
;
STRING_LITERAL(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_8, "| | | | | | | | |", 17);
STRING_LITERAL(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_9, "\343\200\220", 3);
STRING_LITERAL(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_10, " - ", 3);
STRING_LITERAL(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_11, "\343\200\221", 3);
STRING_LITERAL(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_13, "\351\273\222\343\201\256\345\213\235\343\201\241!!", 14);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_12 = {((NimStringDesc*) &TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_13)}
;
STRING_LITERAL(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_15, "\347\231\275\343\201\256\345\213\235\343\201\241!!", 14);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_14 = {((NimStringDesc*) &TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_15)}
;
STRING_LITERAL(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_17, "\345\274\225\343\201\215\345\210\206\343\201\221!!", 14);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_16 = {((NimStringDesc*) &TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_17)}
;
STRING_LITERAL(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_19, "\343\200\220\351\273\222\347\225\252\343\201\214\343\202\271\343\202\255\343\203\203\343\203\227\343\201\225\343\202\214\343\201\276\343\201\227\343\201\237\343\200\221", 42);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_18 = {((NimStringDesc*) &TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_19)}
;
STRING_LITERAL(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_21, "\343\200\220\347\231\275\347\225\252\343\201\214\343\202\271\343\202\255\343\203\203\343\203\227\343\201\225\343\202\214\343\201\276\343\201\227\343\201\237\343\200\221", 42);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_20 = {((NimStringDesc*) &TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_21)}
;

N_LIB_PRIVATE N_NIMCALL(NI, convert_input_r1IZlm9cBhFRGirXlHo4Wsw)(NIM_CHAR c) {
	NI result;
	result = (NI)0;
	switch (((NU8)(c))) {
	case 65:
	case 97:
	case 49:
	{
		result = ((NI) 1);
	}
	break;
	case 66:
	case 98:
	case 50:
	{
		result = ((NI) 2);
	}
	break;
	case 67:
	case 99:
	case 51:
	{
		result = ((NI) 3);
	}
	break;
	case 68:
	case 100:
	case 52:
	{
		result = ((NI) 4);
	}
	break;
	case 69:
	case 101:
	case 53:
	{
		result = ((NI) 5);
	}
	break;
	case 70:
	case 102:
	case 54:
	{
		result = ((NI) 6);
	}
	break;
	case 71:
	case 103:
	case 55:
	{
		result = ((NI) 7);
	}
	break;
	case 72:
	case 104:
	case 56:
	{
		result = ((NI) 8);
	}
	break;
	default:
	{
	}
	break;
	}
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, inputPosN_3tUdVKmL5NR9be6NvrCHtSg)(NU64 black, NU64 white, NIM_BOOL blackTurn) {
	NI result;
	NimStringDesc* line;
	NI x;
	NI y;
	result = (NI)0;
	echoBinSafe(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_2, 1);
	line = readLine_fPRnXwDTqtynUYGl4OixAg(stdin);
	x = convert_input_r1IZlm9cBhFRGirXlHo4Wsw(line->data[((NI) 0)]);
	y = convert_input_r1IZlm9cBhFRGirXlHo4Wsw(line->data[((NI) 1)]);
	result = (NI)((NI)((NI)(y - ((NI) 1)) * ((NI) 8)) + (NI)(x - ((NI) 1)));
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(void, display_Qt1m089bSGE5Df0MPKWgUGQ)(NU64 black, NU64 white, NIM_BOOL blackTurn) {
	NimStringDesc* i_row;
	NU64 putBoard;
	NU64 tmpBlack;
	NU64 tmpWhite;
	NU64 tmpPutBoard;
	i_row = (NimStringDesc*)0;
	putBoard = (NU64)0;
	tmpBlack = (NU64)0;
	tmpWhite = (NU64)0;
	tmpPutBoard = (NU64)0;
	{
		if (!blackTurn) goto LA3_;
		putBoard = getPutBoard_zeO1KqsRtyEbP9bosMoaBIw(black, white);
	}
	goto LA1_;
	LA3_: ;
	{
		putBoard = getPutBoard_zeO1KqsRtyEbP9bosMoaBIw(white, black);
	}
	LA1_: ;
	echoBinSafe(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_4, 1);
	echoBinSafe(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_6, 1);
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				NimStringDesc* fmtRes;
				tyArray_nHXaesL0DJZHyVS07ARPRA T24_;
				if (!(i_2 < ((NI) 8))) goto LA8;
				i = i_2;
				fmtRes = rawNewString(((NI) 32));
				add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) ((NI)(i + ((NI) 1)))));
				fmtRes = resizeString(fmtRes, 17);
appendString(fmtRes, ((NimStringDesc*) &TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_8));
				i_row = copyString(fmtRes);
				tmpBlack = (NU64)((NU64)(black) >> (NU64)((NI)(i * ((NI) 8))));
				tmpWhite = (NU64)((NU64)(white) >> (NU64)((NI)(i * ((NI) 8))));
				tmpPutBoard = (NU64)((NU64)(putBoard) >> (NU64)((NI)(i * ((NI) 8))));
				{
					NI j;
					NI i_3;
					j = (NI)0;
					i_3 = ((NI) 0);
					{
						while (1) {
							if (!(i_3 < ((NI) 8))) goto LA11;
							j = i_3;
							{
								if (!!(((NU64)((NU64)((NU64)(tmpBlack) >> (NU64)(j)) & 1ULL) == ((NI) 0)))) goto LA14_;
								i_row->data[(NI)((NI)(j * ((NI) 2)) + ((NI) 2))] = 98;
							}
							LA14_: ;
							{
								if (!!(((NU64)((NU64)((NU64)(tmpWhite) >> (NU64)(j)) & 1ULL) == ((NI) 0)))) goto LA18_;
								i_row->data[(NI)((NI)(j * ((NI) 2)) + ((NI) 2))] = 119;
							}
							LA18_: ;
							{
								if (!!(((NU64)((NU64)((NU64)(tmpPutBoard) >> (NU64)(j)) & 1ULL) == ((NI) 0)))) goto LA22_;
								i_row->data[(NI)((NI)(j * ((NI) 2)) + ((NI) 2))] = 46;
							}
							LA22_: ;
							i_3 += ((NI) 1);
						} LA11: ;
					}
				}
				memset((void*)T24_, 0, sizeof(T24_));
				T24_[0] = copyString(i_row);
				echoBinSafe(T24_, 1);
				echoBinSafe(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_6, 1);
				i_2 += ((NI) 1);
			} LA8: ;
		}
	}
}

N_LIB_PRIVATE N_NIMCALL(void, outputEnd_WuQfz5YK6r9bmPW6neoLlsA)(NU64 black, NU64 white) {
	NI black_n;
	NI white_n;
	tyArray_nHXaesL0DJZHyVS07ARPRA T1_;
	NimStringDesc* fmtRes;
	black_n = count_Na1w7t9aRHVrWznkd3g2YGQ(black);
	white_n = count_Na1w7t9aRHVrWznkd3g2YGQ(white);
	memset((void*)T1_, 0, sizeof(T1_));
	fmtRes = rawNewString(((NI) 47));
	fmtRes = resizeString(fmtRes, 3);
appendString(fmtRes, ((NimStringDesc*) &TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_9));
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (black_n)));
	fmtRes = resizeString(fmtRes, 3);
appendString(fmtRes, ((NimStringDesc*) &TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_10));
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (white_n)));
	fmtRes = resizeString(fmtRes, 3);
appendString(fmtRes, ((NimStringDesc*) &TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_11));
	T1_[0] = copyString(fmtRes);
	echoBinSafe(T1_, 1);
	{
		if (!(white_n < black_n)) goto LA4_;
		echoBinSafe(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_12, 1);
	}
	goto LA2_;
	LA4_: ;
	{
		if (!(black_n < white_n)) goto LA7_;
		echoBinSafe(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_14, 1);
	}
	goto LA2_;
	LA7_: ;
	{
		echoBinSafe(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_16, 1);
	}
	LA2_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, outputSkip_kAY5g2jlWBy9bcYC2UKdPww)(NIM_BOOL blackTurn) {
	{
		if (!blackTurn) goto LA3_;
		echoBinSafe(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_18, 1);
	}
	goto LA1_;
	LA3_: ;
	{
		echoBinSafe(TM_Jqr3Zg0sl9a5TlIH2UBi9cSw_20, 1);
	}
	LA1_: ;
}
NIM_EXTERNC N_NOINLINE(void, unknown_command_lineInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, unknown_command_lineDatInit000)(void) {
}

