/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/kaneko_takayuki/.choosenim/toolchains/nim-0.18.0/lib -o /Users/kaneko_takayuki/MyProgram/ReversiAI/src/nimcache/core.o /Users/kaneko_takayuki/MyProgram/ReversiAI/src/nimcache/core.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_GviMuKbe9c3Hsi9c4x4m9avrw tyTuple_GviMuKbe9c3Hsi9c4x4m9avrw;
struct tyTuple_GviMuKbe9c3Hsi9c4x4m9avrw {
NU64 Field0;
NU64 Field1;
};
N_LIB_PRIVATE N_NIMCALL(NU64, getRevBoard_OZmhNZjQV9bCDasDWYYkfqw)(NU64 me, NU64 op, NU64 pos);
NIM_CONST tyTuple_GviMuKbe9c3Hsi9c4x4m9avrw TM_mQ2oTiYUSnGEF9b6J8NupNQ_2 = {34628173824ULL,
68853694464ULL}
;

N_LIB_PRIVATE N_NIMCALL(NU64, getPutBoard_zeO1KqsRtyEbP9bosMoaBIw)(NU64 me, NU64 op) {
	NU64 result;
	NU64 blank;
	NU64 masked_op;
	NU64 tmp;
	result = (NU64)0;
	result = 0ULL;
	blank = (NU64)((NU64) ~((NU64)(me | op)));
	masked_op = (NU64)0;
	tmp = (NU64)0;
	masked_op = (NU64)(op & 9114861777597660798ULL);
	tmp = (NU64)(masked_op & (NU64)((NU64)(me) << (NU64)(((NI) 1))));
	{
		NI _;
		NI i;
		_ = (NI)0;
		i = ((NI) 0);
		{
			while (1) {
				if (!(i < ((NI) 5))) goto LA3;
				_ = i;
				tmp = (NU64)(tmp | (NU64)(masked_op & (NU64)((NU64)(tmp) << (NU64)(((NI) 1)))));
				i += ((NI) 1);
			} LA3: ;
		}
	}
	result = (NU64)(result | (NU64)(blank & (NU64)((NU64)(tmp) << (NU64)(((NI) 1)))));
	tmp = (NU64)(masked_op & (NU64)((NU64)(me) >> (NU64)(((NI) 1))));
	{
		NI __2;
		NI i_2;
		__2 = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < ((NI) 5))) goto LA6;
				__2 = i_2;
				tmp = (NU64)(tmp | (NU64)(masked_op & (NU64)((NU64)(tmp) >> (NU64)(((NI) 1)))));
				i_2 += ((NI) 1);
			} LA6: ;
		}
	}
	result = (NU64)(result | (NU64)(blank & (NU64)((NU64)(tmp) >> (NU64)(((NI) 1)))));
	masked_op = (NU64)(op & 9114861777597660798ULL);
	tmp = (NU64)(masked_op & (NU64)((NU64)(me) << (NU64)(((NI) 8))));
	{
		NI __3;
		NI i_3;
		__3 = (NI)0;
		i_3 = ((NI) 0);
		{
			while (1) {
				if (!(i_3 < ((NI) 5))) goto LA9;
				__3 = i_3;
				tmp = (NU64)(tmp | (NU64)(masked_op & (NU64)((NU64)(tmp) << (NU64)(((NI) 8)))));
				i_3 += ((NI) 1);
			} LA9: ;
		}
	}
	result = (NU64)(result | (NU64)(blank & (NU64)((NU64)(tmp) << (NU64)(((NI) 8)))));
	tmp = (NU64)(masked_op & (NU64)((NU64)(me) >> (NU64)(((NI) 8))));
	{
		NI __4;
		NI i_4;
		__4 = (NI)0;
		i_4 = ((NI) 0);
		{
			while (1) {
				if (!(i_4 < ((NI) 5))) goto LA12;
				__4 = i_4;
				tmp = (NU64)(tmp | (NU64)(masked_op & (NU64)((NU64)(tmp) >> (NU64)(((NI) 8)))));
				i_4 += ((NI) 1);
			} LA12: ;
		}
	}
	result = (NU64)(result | (NU64)(blank & (NU64)((NU64)(tmp) >> (NU64)(((NI) 8)))));
	masked_op = (NU64)(op & 35604928818740736ULL);
	tmp = (NU64)(masked_op & (NU64)((NU64)(me) << (NU64)(((NI) 7))));
	{
		NI __5;
		NI i_5;
		__5 = (NI)0;
		i_5 = ((NI) 0);
		{
			while (1) {
				if (!(i_5 < ((NI) 5))) goto LA15;
				__5 = i_5;
				tmp = (NU64)(tmp | (NU64)(masked_op & (NU64)((NU64)(tmp) << (NU64)(((NI) 7)))));
				i_5 += ((NI) 1);
			} LA15: ;
		}
	}
	result = (NU64)(result | (NU64)(blank & (NU64)((NU64)(tmp) << (NU64)(((NI) 7)))));
	tmp = (NU64)(masked_op & (NU64)((NU64)(me) << (NU64)(((NI) 9))));
	{
		NI __6;
		NI i_6;
		__6 = (NI)0;
		i_6 = ((NI) 0);
		{
			while (1) {
				if (!(i_6 < ((NI) 5))) goto LA18;
				__6 = i_6;
				tmp = (NU64)(tmp | (NU64)(masked_op & (NU64)((NU64)(tmp) << (NU64)(((NI) 9)))));
				i_6 += ((NI) 1);
			} LA18: ;
		}
	}
	result = (NU64)(result | (NU64)(blank & (NU64)((NU64)(tmp) << (NU64)(((NI) 9)))));
	tmp = (NU64)(masked_op & (NU64)((NU64)(me) >> (NU64)(((NI) 9))));
	{
		NI __7;
		NI i_7;
		__7 = (NI)0;
		i_7 = ((NI) 0);
		{
			while (1) {
				if (!(i_7 < ((NI) 5))) goto LA21;
				__7 = i_7;
				tmp = (NU64)(tmp | (NU64)(masked_op & (NU64)((NU64)(tmp) >> (NU64)(((NI) 9)))));
				i_7 += ((NI) 1);
			} LA21: ;
		}
	}
	result = (NU64)(result | (NU64)(blank & (NU64)((NU64)(tmp) >> (NU64)(((NI) 9)))));
	tmp = (NU64)(masked_op & (NU64)((NU64)(me) >> (NU64)(((NI) 7))));
	{
		NI __8;
		NI i_8;
		__8 = (NI)0;
		i_8 = ((NI) 0);
		{
			while (1) {
				if (!(i_8 < ((NI) 5))) goto LA24;
				__8 = i_8;
				tmp = (NU64)(tmp | (NU64)(masked_op & (NU64)((NU64)(tmp) >> (NU64)(((NI) 7)))));
				i_8 += ((NI) 1);
			} LA24: ;
		}
	}
	result = (NU64)(result | (NU64)(blank & (NU64)((NU64)(tmp) >> (NU64)(((NI) 7)))));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NU64, getRevBoard_OZmhNZjQV9bCDasDWYYkfqw)(NU64 me, NU64 op, NU64 pos) {
	NU64 result;
	NU64 blank;
	NI i;
	NU64 masked_op;
	NU64 rev_cand;
	result = (NU64)0;
	result = 0ULL;
	blank = (NU64)((NU64) ~((NU64)(me | op)));
	i = (NI)0;
	masked_op = (NU64)0;
	rev_cand = (NU64)0;
	masked_op = (NU64)(op & 9114861777597660798ULL);
	i = ((NI) 1);
	rev_cand = 0ULL;
	{
		while (1) {
			if (!!(((NU64)((NU64)((NU64)(pos) << (NU64)(i)) & masked_op) == ((NI) 0)))) goto LA2;
			rev_cand = (NU64)(rev_cand | (NU64)((NU64)(pos) << (NU64)(i)));
			i += ((NI) 1);
		} LA2: ;
	}
	{
		if (!!(((NU64)((NU64)((NU64)(pos) << (NU64)(i)) & me) == ((NI) 0)))) goto LA5_;
		result = (NU64)(result | rev_cand);
	}
	LA5_: ;
	i = ((NI) 1);
	rev_cand = 0ULL;
	{
		while (1) {
			if (!!(((NU64)((NU64)((NU64)(pos) >> (NU64)(i)) & masked_op) == ((NI) 0)))) goto LA8;
			rev_cand = (NU64)(rev_cand | (NU64)((NU64)(pos) >> (NU64)(i)));
			i += ((NI) 1);
		} LA8: ;
	}
	{
		if (!!(((NU64)((NU64)((NU64)(pos) >> (NU64)(i)) & me) == ((NI) 0)))) goto LA11_;
		result = (NU64)(result | rev_cand);
	}
	LA11_: ;
	masked_op = (NU64)(op & 72057594037927680ULL);
	i = ((NI) 1);
	rev_cand = 0ULL;
	{
		while (1) {
			if (!!(((NU64)((NU64)((NU64)(pos) >> (NU64)((NI)(i * ((NI) 8)))) & masked_op) == ((NI) 0)))) goto LA14;
			rev_cand = (NU64)(rev_cand | (NU64)((NU64)(pos) >> (NU64)((NI)(i * ((NI) 8)))));
			i += ((NI) 1);
		} LA14: ;
	}
	{
		if (!!(((NU64)((NU64)((NU64)(pos) >> (NU64)((NI)(i * ((NI) 8)))) & me) == ((NI) 0)))) goto LA17_;
		result = (NU64)(result | rev_cand);
	}
	LA17_: ;
	i = ((NI) 1);
	rev_cand = 0ULL;
	{
		while (1) {
			if (!!(((NU64)((NU64)((NU64)(pos) << (NU64)((NI)(i * ((NI) 8)))) & masked_op) == ((NI) 0)))) goto LA20;
			rev_cand = (NU64)(rev_cand | (NU64)((NU64)(pos) << (NU64)((NI)(i * ((NI) 8)))));
			i += ((NI) 1);
		} LA20: ;
	}
	{
		if (!!(((NU64)((NU64)((NU64)(pos) << (NU64)((NI)(i * ((NI) 8)))) & me) == ((NI) 0)))) goto LA23_;
		result = (NU64)(result | rev_cand);
	}
	LA23_: ;
	masked_op = (NU64)(op & 35604928818740736ULL);
	i = ((NI) 1);
	rev_cand = 0ULL;
	{
		while (1) {
			if (!!(((NU64)((NU64)((NU64)(pos) << (NU64)((NI)(i * ((NI) 7)))) & masked_op) == ((NI) 0)))) goto LA26;
			rev_cand = (NU64)(rev_cand | (NU64)((NU64)(pos) << (NU64)((NI)(i * ((NI) 7)))));
			i += ((NI) 1);
		} LA26: ;
	}
	{
		if (!!(((NU64)((NU64)((NU64)(pos) << (NU64)((NI)(i * ((NI) 7)))) & me) == ((NI) 0)))) goto LA29_;
		result = (NU64)(result | rev_cand);
	}
	LA29_: ;
	i = ((NI) 1);
	rev_cand = 0ULL;
	{
		while (1) {
			if (!!(((NU64)((NU64)((NU64)(pos) << (NU64)((NI)(i * ((NI) 9)))) & masked_op) == ((NI) 0)))) goto LA32;
			rev_cand = (NU64)(rev_cand | (NU64)((NU64)(pos) << (NU64)((NI)(i * ((NI) 9)))));
			i += ((NI) 1);
		} LA32: ;
	}
	{
		if (!!(((NU64)((NU64)((NU64)(pos) << (NU64)((NI)(i * ((NI) 9)))) & me) == ((NI) 0)))) goto LA35_;
		result = (NU64)(result | rev_cand);
	}
	LA35_: ;
	i = ((NI) 1);
	rev_cand = 0ULL;
	{
		while (1) {
			if (!!(((NU64)((NU64)((NU64)(pos) >> (NU64)((NI)(i * ((NI) 9)))) & masked_op) == ((NI) 0)))) goto LA38;
			rev_cand = (NU64)(rev_cand | (NU64)((NU64)(pos) >> (NU64)((NI)(i * ((NI) 9)))));
			i += ((NI) 1);
		} LA38: ;
	}
	{
		if (!!(((NU64)((NU64)((NU64)(pos) >> (NU64)((NI)(i * ((NI) 9)))) & me) == ((NI) 0)))) goto LA41_;
		result = (NU64)(result | rev_cand);
	}
	LA41_: ;
	i = ((NI) 1);
	rev_cand = 0ULL;
	{
		while (1) {
			if (!!(((NU64)((NU64)((NU64)(pos) >> (NU64)((NI)(i * ((NI) 7)))) & masked_op) == ((NI) 0)))) goto LA44;
			rev_cand = (NU64)(rev_cand | (NU64)((NU64)(pos) >> (NU64)((NI)(i * ((NI) 7)))));
			i += ((NI) 1);
		} LA44: ;
	}
	{
		if (!!(((NU64)((NU64)((NU64)(pos) >> (NU64)((NI)(i * ((NI) 7)))) & me) == ((NI) 0)))) goto LA47_;
		result = (NU64)(result | rev_cand);
	}
	LA47_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_GviMuKbe9c3Hsi9c4x4m9avrw, init_board_0iVYRxu4VHdpeO9bvKo7ilg)(void) {
	tyTuple_GviMuKbe9c3Hsi9c4x4m9avrw result;
	memset((void*)(&result), 0, sizeof(result));
	result = TM_mQ2oTiYUSnGEF9b6J8NupNQ_2;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, count_Na1w7t9aRHVrWznkd3g2YGQ)(NU64 x) {
	NI result;
	NU64 t;
	result = (NI)0;
	t = (NU64)((NU64)((NU64)(x & 6148914691236517205ULL)) + (NU64)((NU64)((NU64)((NU64)(x) >> (NU64)(((NI) 1))) & 6148914691236517205ULL)));
	t = (NU64)((NU64)((NU64)(t & 3689348814741910323ULL)) + (NU64)((NU64)((NU64)((NU64)(t) >> (NU64)(((NI) 2))) & 3689348814741910323ULL)));
	t = (NU64)((NU64)((NU64)(t & 1085102592571150095ULL)) + (NU64)((NU64)((NU64)((NU64)(t) >> (NU64)(((NI) 4))) & 1085102592571150095ULL)));
	t = (NU64)((NU64)((NU64)(t & 71777214294589695ULL)) + (NU64)((NU64)((NU64)((NU64)(t) >> (NU64)(((NI) 8))) & 71777214294589695ULL)));
	t = (NU64)((NU64)((NU64)(t & 281470681808895ULL)) + (NU64)((NU64)((NU64)((NU64)(t) >> (NU64)(((NI) 16))) & 281470681808895ULL)));
	t = (NU64)((NU64)((NU64)(t & 4294967295ULL)) + (NU64)((NU64)((NU64)((NU64)(t) >> (NU64)(((NI) 32))) & 4294967295ULL)));
	result = ((NI) (t));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_GviMuKbe9c3Hsi9c4x4m9avrw, putStone_Wok9aJYLA0NcSRmn9c4v77sQ)(NU64 black, NU64 white, NI posN, NIM_BOOL blackTurn) {
	tyTuple_GviMuKbe9c3Hsi9c4x4m9avrw result;
	NU64 rev;
	NU64 pos;
	memset((void*)(&result), 0, sizeof(result));
	rev = (NU64)0;
	pos = ((NU64) ((NU)((NU64)(((NU) 1)) << (NU64)(posN))));
	{
		NU64 new_black;
		NU64 new_white;
		if (!blackTurn) goto LA3_;
		rev = getRevBoard_OZmhNZjQV9bCDasDWYYkfqw(black, white, pos);
		new_black = (NU64)(black ^ (NU64)(pos | rev));
		new_white = (NU64)(white ^ rev);
		result.Field0 = new_black;
		result.Field1 = new_white;
	}
	goto LA1_;
	LA3_: ;
	{
		NU64 new_white_2;
		NU64 new_black_2;
		rev = getRevBoard_OZmhNZjQV9bCDasDWYYkfqw(white, black, pos);
		new_white_2 = (NU64)(white ^ (NU64)(pos | rev));
		new_black_2 = (NU64)(black ^ rev);
		result.Field0 = new_black_2;
		result.Field1 = new_white_2;
	}
	LA1_: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_coreInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, unknown_coreDatInit000)(void) {
}

