/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/kaneko_takayuki/.choosenim/toolchains/nim-0.18.0/lib -o /Users/kaneko_takayuki/MyProgram/ReversiAI/src/nimcache/evaluate.o /Users/kaneko_takayuki/MyProgram/ReversiAI/src/nimcache/evaluate.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef NI tyArray_SLBTEB08vk46ttuRaTxAYw[64];
N_LIB_PRIVATE N_NIMCALL(NU64, getPutBoard_zeO1KqsRtyEbP9bosMoaBIw)(NU64 me, NU64 op);
extern NIM_CONST tyArray_SLBTEB08vk46ttuRaTxAYw VALUE_TABLE_fpAvbcnquW9b558jo1cCeDg;

N_LIB_PRIVATE N_NIMCALL(NI, evaluateWithPosition_WTnc1bOa8JXsHTNPzd5J8A)(NU64 me, NU64 op) {
	NI result;
	NI score;
	result = (NI)0;
	score = ((NI) 0);
	{
		NI i;
		NI res;
		i = (NI)0;
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= ((NI) 63))) goto LA3;
				i = res;
				score += (NI)((NI)(VALUE_TABLE_fpAvbcnquW9b558jo1cCeDg[(i)- 0] * ((NI) ((NU64)((NU64)((NU64)(me) >> (NU64)(i)) & 1ULL)))) - (NI)(VALUE_TABLE_fpAvbcnquW9b558jo1cCeDg[(i)- 0] * ((NI) ((NU64)((NU64)((NU64)(op) >> (NU64)(i)) & 1ULL)))));
				res += ((NI) 1);
			} LA3: ;
		}
	}
	result = score;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, evaluateWithPutN_WTnc1bOa8JXsHTNPzd5J8A_2)(NU64 me, NU64 op) {
	NI result;
	NU64 mePutBoard;
	NU64 opPutBoard;
	NI score;
	result = (NI)0;
	mePutBoard = getPutBoard_zeO1KqsRtyEbP9bosMoaBIw(me, op);
	opPutBoard = getPutBoard_zeO1KqsRtyEbP9bosMoaBIw(op, me);
	score = ((NI) 0);
	{
		NI i;
		NI res;
		i = (NI)0;
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= ((NI) 63))) goto LA3;
				i = res;
				score += ((NI) ((NU64)((NU64)((NU64)((NU64)((NU64)(mePutBoard) >> (NU64)(i)) & 1ULL)) - (NU64)((NU64)((NU64)((NU64)(opPutBoard) >> (NU64)(i)) & 1ULL)))));
				res += ((NI) 1);
			} LA3: ;
		}
	}
	result = score;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_evaluateInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, unknown_evaluateDatInit000)(void) {
}

