/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/kaneko_takayuki/.choosenim/toolchains/nim-0.18.0/lib -o /Users/kaneko_takayuki/MyProgram/ReversiAI/src/nimcache/game.o /Users/kaneko_takayuki/MyProgram/ReversiAI/src/nimcache/game.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_GviMuKbe9c3Hsi9c4x4m9avrw tyTuple_GviMuKbe9c3Hsi9c4x4m9avrw;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct {
N_NIMCALL_PTR(NI, ClP_0) (NU64 black, NU64 white, NIM_BOOL blackTurn, void* ClE_0);
void* ClE_0;
} tyProc_DyD4r9cv7AC5jKJQb1rPz0A;
struct tyTuple_GviMuKbe9c3Hsi9c4x4m9avrw {
NU64 Field0;
NU64 Field1;
};
typedef N_CLOSURE_PTR(NI, TM_xptSX7JJDIzAP7dVr1Oe9cw_2) (NU64 black, NU64 white, NIM_BOOL blackTurn);
typedef N_CLOSURE_PTR(NI, TM_xptSX7JJDIzAP7dVr1Oe9cw_3) (NU64 black, NU64 white, NIM_BOOL blackTurn);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
N_LIB_PRIVATE N_NIMCALL(NU64, getPutBoard_zeO1KqsRtyEbP9bosMoaBIw)(NU64 me, NU64 op);
N_LIB_PRIVATE N_NIMCALL(tyTuple_GviMuKbe9c3Hsi9c4x4m9avrw, init_board_0iVYRxu4VHdpeO9bvKo7ilg)(void);
N_LIB_PRIVATE N_NIMCALL(void, display_Qt1m089bSGE5Df0MPKWgUGQ)(NU64 black, NU64 white, NIM_BOOL blackTurn);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isEnd_GohnLDQTdtUYriy1iAaBNA)(NU64 black, NU64 white);
N_LIB_PRIVATE N_NIMCALL(void, outputEnd_WuQfz5YK6r9bmPW6neoLlsA)(NU64 black, NU64 white);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, skipTurn_XGNqoSnVSfZkCklP5jeXog)(NU64 black, NU64 white, NIM_BOOL blackTurn);
N_LIB_PRIVATE N_NIMCALL(void, outputSkip_kAY5g2jlWBy9bcYC2UKdPww)(NIM_BOOL blackTurn);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, add_IbYQ9cTcoQ89aIwM2IEYGMng)(NimStringDesc** result, NI64 x);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, enablePut_DyCr5lO4MNSB7odwpDlacA)(NU64 black, NU64 white, NIM_BOOL blackTurn, NI posN);
N_LIB_PRIVATE N_NIMCALL(tyTuple_GviMuKbe9c3Hsi9c4x4m9avrw, putStone_Wok9aJYLA0NcSRmn9c4v77sQ)(NU64 black, NU64 white, NI posN, NIM_BOOL blackTurn);
STRING_LITERAL(TM_xptSX7JJDIzAP7dVr1Oe9cw_4, "posN: ", 6);
STRING_LITERAL(TM_xptSX7JJDIzAP7dVr1Oe9cw_6, "\343\200\220!\345\205\245\345\212\233\343\201\225\343\202\214\343\201\237\345\240\264\346\211\200\343\201\257\346\234\211\345\212\271\343\201\247\343\201\257\343\201\202\343\202\212\343\201\276\343\201\233\343\202\223!\343\200\221", 59);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_xptSX7JJDIzAP7dVr1Oe9cw_5 = {((NimStringDesc*) &TM_xptSX7JJDIzAP7dVr1Oe9cw_6)}
;

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isEnd_GohnLDQTdtUYriy1iAaBNA)(NU64 black, NU64 white) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NU64 T2_;
	NU64 T4_;
	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T2_ = (NU64)0;
	T2_ = getPutBoard_zeO1KqsRtyEbP9bosMoaBIw(black, white);
	T1_ = (T2_ == ((NI) 0));
	if (!(T1_)) goto LA3_;
	T4_ = (NU64)0;
	T4_ = getPutBoard_zeO1KqsRtyEbP9bosMoaBIw(white, black);
	T1_ = (T4_ == ((NI) 0));
	LA3_: ;
	result = T1_;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, skipTurn_XGNqoSnVSfZkCklP5jeXog)(NU64 black, NU64 white, NIM_BOOL blackTurn) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		NU64 T5_;
		if (!blackTurn) goto LA3_;
		T5_ = (NU64)0;
		T5_ = getPutBoard_zeO1KqsRtyEbP9bosMoaBIw(black, white);
		result = (T5_ == ((NI) 0));
	}
	goto LA1_;
	LA3_: ;
	{
		NU64 T7_;
		T7_ = (NU64)0;
		T7_ = getPutBoard_zeO1KqsRtyEbP9bosMoaBIw(white, black);
		result = (T7_ == ((NI) 0));
	}
	LA1_: ;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, enablePut_DyCr5lO4MNSB7odwpDlacA)(NU64 black, NU64 white, NIM_BOOL blackTurn, NI posN) {
	NIM_BOOL result;
	NU64 pos;
	result = (NIM_BOOL)0;
	pos = ((NU64) ((NU)((NU64)(((NU) 1)) << (NU64)(posN))));
	{
		NU64 T5_;
		if (!blackTurn) goto LA3_;
		T5_ = (NU64)0;
		T5_ = getPutBoard_zeO1KqsRtyEbP9bosMoaBIw(black, white);
		result = !(((NU64)(T5_ & pos) == ((NI) 0)));
	}
	goto LA1_;
	LA3_: ;
	{
		NU64 T7_;
		T7_ = (NU64)0;
		T7_ = getPutBoard_zeO1KqsRtyEbP9bosMoaBIw(white, black);
		result = !(((NU64)(T7_ & pos) == ((NI) 0)));
	}
	LA1_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, gameStart_VGxPDTVR71IU5iZr1yJvqA)(tyProc_DyD4r9cv7AC5jKJQb1rPz0A blackInput, tyProc_DyD4r9cv7AC5jKJQb1rPz0A whiteInput) {
	tyTuple_GviMuKbe9c3Hsi9c4x4m9avrw T1_;
	NU64 black;
	NU64 white;
	NIM_BOOL blackTurn;
	T1_ = init_board_0iVYRxu4VHdpeO9bvKo7ilg();
	black = T1_.Field0;
	white = T1_.Field1;
	blackTurn = NIM_TRUE;
	{
		while (1) {
			{
				NI posN;
				tyTuple_GviMuKbe9c3Hsi9c4x4m9avrw _;
				display_Qt1m089bSGE5Df0MPKWgUGQ(black, white, blackTurn);
				{
					NIM_BOOL T7_;
					T7_ = (NIM_BOOL)0;
					T7_ = isEnd_GohnLDQTdtUYriy1iAaBNA(black, white);
					if (!T7_) goto LA8_;
					outputEnd_WuQfz5YK6r9bmPW6neoLlsA(black, white);
					goto LA2;
				}
				LA8_: ;
				{
					NIM_BOOL T12_;
					T12_ = (NIM_BOOL)0;
					T12_ = skipTurn_XGNqoSnVSfZkCklP5jeXog(black, white, blackTurn);
					if (!T12_) goto LA13_;
					outputSkip_kAY5g2jlWBy9bcYC2UKdPww(blackTurn);
					blackTurn = !(blackTurn);
					goto LA4;
				}
				LA13_: ;
				posN = (NI)0;
				{
					while (1) {
						tyArray_nHXaesL0DJZHyVS07ARPRA T22_;
						NimStringDesc* fmtRes;
						{
							if (!blackTurn) goto LA19_;
							posN = blackInput.ClE_0? blackInput.ClP_0(black, white, blackTurn, blackInput.ClE_0):((TM_xptSX7JJDIzAP7dVr1Oe9cw_2)(blackInput.ClP_0))(black, white, blackTurn);
						}
						goto LA17_;
						LA19_: ;
						{
							posN = whiteInput.ClE_0? whiteInput.ClP_0(black, white, blackTurn, whiteInput.ClE_0):((TM_xptSX7JJDIzAP7dVr1Oe9cw_3)(whiteInput.ClP_0))(black, white, blackTurn);
						}
						LA17_: ;
						memset((void*)T22_, 0, sizeof(T22_));
						fmtRes = rawNewString(((NI) 22));
						fmtRes = resizeString(fmtRes, 6);
appendString(fmtRes, ((NimStringDesc*) &TM_xptSX7JJDIzAP7dVr1Oe9cw_4));
						add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (posN)));
						T22_[0] = copyString(fmtRes);
						echoBinSafe(T22_, 1);
						{
							NIM_BOOL T25_;
							T25_ = (NIM_BOOL)0;
							T25_ = enablePut_DyCr5lO4MNSB7odwpDlacA(black, white, blackTurn, posN);
							if (!T25_) goto LA26_;
							goto LA15;
						}
						LA26_: ;
						echoBinSafe(TM_xptSX7JJDIzAP7dVr1Oe9cw_5, 1);
					}
				} LA15: ;
				_ = putStone_Wok9aJYLA0NcSRmn9c4v77sQ(black, white, posN, blackTurn);
				black = _.Field0;
				white = _.Field1;
				blackTurn = !(blackTurn);
			} LA4: ;
		}
	} LA2: ;
}
NIM_EXTERNC N_NOINLINE(void, unknown_gameInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, unknown_gameDatInit000)(void) {
}

