/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/kaneko_takayuki/.choosenim/toolchains/nim-0.18.0/lib -o /Users/kaneko_takayuki/MyProgram/ReversiAI/src/nimcache/main.o /Users/kaneko_takayuki/MyProgram/ReversiAI/src/nimcache/main.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_2uzTbg8jwom7zHhmM2RgHg tyTuple_2uzTbg8jwom7zHhmM2RgHg;
typedef struct tyObject_Env_maindotnim__sO5O0Qy9bzKs0atwA6HUBAw tyObject_Env_maindotnim__sO5O0Qy9bzKs0atwA6HUBAw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct RootObj RootObj;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct {
N_NIMCALL_PTR(NI, ClP_0) (NU64 black, NU64 white, NIM_BOOL blackTurn, void* ClE_0);
void* ClE_0;
} tyProc_DyD4r9cv7AC5jKJQb1rPz0A;
struct tyTuple_2uzTbg8jwom7zHhmM2RgHg {
void* Field0;
tyObject_Env_maindotnim__sO5O0Qy9bzKs0atwA6HUBAw* Field1;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_Env_maindotnim__sO5O0Qy9bzKs0atwA6HUBAw {
  RootObj Sup;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef N_CLOSURE_PTR(NI, TM_V45tF8B8NBcxFcjfe7lhBw_4) (NU64 black, NU64 white, NIM_BOOL blackTurn, void* ClE_0);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef N_CLOSURE_PTR(NI, TM_V45tF8B8NBcxFcjfe7lhBw_6) (NU64 black, NU64 white, NIM_BOOL blackTurn, void* ClE_0);
typedef NU8 tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w {
  RootObj Sup;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* cmd;
NI pos;
NimStringDesc* remainingShortOptions;
tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw kind;
NimStringDesc* key;
NimStringDesc* val;
};
typedef N_CLOSURE_PTR(NI, TM_V45tF8B8NBcxFcjfe7lhBw_11) (NU64 black, NU64 white, NIM_BOOL blackTurn, void* ClE_0);
typedef N_CLOSURE_PTR(NI, TM_V45tF8B8NBcxFcjfe7lhBw_13) (NU64 black, NU64 white, NIM_BOOL blackTurn, void* ClE_0);
typedef N_CLOSURE_PTR(NI, TM_V45tF8B8NBcxFcjfe7lhBw_15) (NU64 black, NU64 white, NIM_BOOL blackTurn, void* ClE_0);
typedef N_CLOSURE_PTR(NI, TM_V45tF8B8NBcxFcjfe7lhBw_16) (NU64 black, NU64 white, NIM_BOOL blackTurn, void* ClE_0);
typedef N_CLOSURE_PTR(NI, TM_V45tF8B8NBcxFcjfe7lhBw_18) (NU64 black, NU64 white, NIM_BOOL blackTurn, void* ClE_0);
typedef N_CLOSURE_PTR(NI, TM_V45tF8B8NBcxFcjfe7lhBw_19) (NU64 black, NU64 white, NIM_BOOL blackTurn, void* ClE_0);
typedef N_CLOSURE_PTR(NI, TM_V45tF8B8NBcxFcjfe7lhBw_21) (NU64 black, NU64 white, NIM_BOOL blackTurn, void* ClE_0);
typedef N_CLOSURE_PTR(NI, TM_V45tF8B8NBcxFcjfe7lhBw_22) (NU64 black, NU64 white, NIM_BOOL blackTurn, void* ClE_0);
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
static N_NIMCALL(void, Marker_tyRef_58EFneeS9at7cA541QCoGAw)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_3)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(NI, choosePosN_FnR9a55ekWIcD5z7wNgKsmQ)(NU64 black, NU64 white, NIM_BOOL blackTurn);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_5)(void);
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_7)(void);
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_8)(void);
N_LIB_PRIVATE N_NIMCALL(void, initOptParser_7ywjeToZhKr9cLpneviH7zg)(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* Result);
N_LIB_PRIVATE N_NIMCALL(void, npo2next)(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* p);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(NI, inputPosN_3tUdVKmL5NR9be6NvrCHtSg)(NU64 black, NU64 white, NIM_BOOL blackTurn);
N_LIB_PRIVATE N_NIMCALL(void, gameStart_VGxPDTVR71IU5iZr1yJvqA)(tyProc_DyD4r9cv7AC5jKJQb1rPz0A blackInput, tyProc_DyD4r9cv7AC5jKJQb1rPz0A whiteInput);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseopt2Init000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseopt2DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_coreInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_coreDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strformatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strformatDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_command_lineInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_command_lineDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_gameInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_gameDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_searchResultInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_searchResultDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_aiConfigInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_aiConfigDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_evaluateInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_evaluateDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_aiInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_aiDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void);
tyProc_DyD4r9cv7AC5jKJQb1rPz0A blackInput_ArmIfnivojEzI3b46HA6Vg;
TNimType NTI_DyD4r9cv7AC5jKJQb1rPz0A_;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_sO5O0Qy9bzKs0atwA6HUBAw_;
TNimType NTI_58EFneeS9at7cA541QCoGAw_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
tyProc_DyD4r9cv7AC5jKJQb1rPz0A whiteInput_48AJqfb5KCSIlBIaaWoCXg;
tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw kind_M529b88sf7uZFsu0KGcAUiw;
NimStringDesc* key_q8si9a8j0iffMMe21H89aknQ;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
NimStringDesc* val_C32W9cnRiWF3VO2YWSagqwQ;
extern TNimType NTI_w3uFmxpwEmgEXFUJjUl10w_;
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_9, "black", 5);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_10, "person", 6);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_12, "ai", 2);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_14, "white", 5);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_17, "b", 1);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_20, "w", 1);
static N_NIMCALL(void, Marker_tyRef_58EFneeS9at7cA541QCoGAw)(void* p, NI op) {
	tyObject_Env_maindotnim__sO5O0Qy9bzKs0atwA6HUBAw* a;
	a = (tyObject_Env_maindotnim__sO5O0Qy9bzKs0atwA6HUBAw*)p;
}
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_3)(void) {
	nimGCvisit((void*)blackInput_ArmIfnivojEzI3b46HA6Vg.ClE_0, 0);
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_5)(void) {
	nimGCvisit((void*)whiteInput_48AJqfb5KCSIlBIaaWoCXg.ClE_0, 0);
}
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_7)(void) {
	nimGCvisit((void*)key_q8si9a8j0iffMMe21H89aknQ, 0);
}
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_8)(void) {
	nimGCvisit((void*)val_C32W9cnRiWF3VO2YWSagqwQ, 0);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_posixDatInit000();
	stdlib_timesDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_parseopt2DatInit000();
	unknown_coreDatInit000();
	stdlib_macrosDatInit000();
	stdlib_unicodeDatInit000();
	stdlib_strformatDatInit000();
	unknown_command_lineDatInit000();
	unknown_gameDatInit000();
	unknown_searchResultDatInit000();
	unknown_aiConfigDatInit000();
	unknown_evaluateDatInit000();
	unknown_aiDatInit000();
	mainDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_posixInit000();
	stdlib_timesInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_parseopt2Init000();
	unknown_coreInit000();
	stdlib_macrosInit000();
	stdlib_unicodeInit000();
	stdlib_strformatInit000();
	unknown_command_lineInit000();
	unknown_gameInit000();
	unknown_searchResultInit000();
	unknown_aiConfigInit000();
	unknown_evaluateInit000();
	unknown_aiInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyProc_DyD4r9cv7AC5jKJQb1rPz0A T1_;
	tyProc_DyD4r9cv7AC5jKJQb1rPz0A T2_;
nimRegisterGlobalMarker(TM_V45tF8B8NBcxFcjfe7lhBw_3);
nimRegisterGlobalMarker(TM_V45tF8B8NBcxFcjfe7lhBw_5);
nimRegisterGlobalMarker(TM_V45tF8B8NBcxFcjfe7lhBw_7);
nimRegisterGlobalMarker(TM_V45tF8B8NBcxFcjfe7lhBw_8);
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.ClP_0 = ((TM_V45tF8B8NBcxFcjfe7lhBw_4) (choosePosN_FnR9a55ekWIcD5z7wNgKsmQ)); T1_.ClE_0 = NIM_NIL;
	asgnRef((void**) (&blackInput_ArmIfnivojEzI3b46HA6Vg.ClE_0), T1_.ClE_0);
	blackInput_ArmIfnivojEzI3b46HA6Vg.ClP_0 = T1_.ClP_0;
	memset((void*)(&T2_), 0, sizeof(T2_));
	T2_.ClP_0 = ((TM_V45tF8B8NBcxFcjfe7lhBw_6) (choosePosN_FnR9a55ekWIcD5z7wNgKsmQ)); T2_.ClE_0 = NIM_NIL;
	asgnRef((void**) (&whiteInput_48AJqfb5KCSIlBIaaWoCXg.ClE_0), T2_.ClE_0);
	whiteInput_48AJqfb5KCSIlBIaaWoCXg.ClP_0 = T2_.ClP_0;
	{
		tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w p;
		memset((void*)(&p), 0, sizeof(p));
		p.Sup.m_type = (&NTI_w3uFmxpwEmgEXFUJjUl10w_);
		initOptParser_7ywjeToZhKr9cLpneviH7zg((&p));
		{
			while (1) {
				NimStringDesc* T10_;
				NimStringDesc* T11_;
				npo2next((&p));
				{
					if (!(p.kind == ((tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 0))) goto LA8_;
					goto LA4;
				}
				LA8_: ;
				kind_M529b88sf7uZFsu0KGcAUiw = p.kind;
				T10_ = (NimStringDesc*)0;
				T10_ = key_q8si9a8j0iffMMe21H89aknQ; key_q8si9a8j0iffMMe21H89aknQ = copyStringRC1(p.key);
				if (T10_) nimGCunrefNoCycle(T10_);
				T11_ = (NimStringDesc*)0;
				T11_ = val_C32W9cnRiWF3VO2YWSagqwQ; val_C32W9cnRiWF3VO2YWSagqwQ = copyStringRC1(p.val);
				if (T11_) nimGCunrefNoCycle(T11_);
				switch (kind_M529b88sf7uZFsu0KGcAUiw) {
				case ((tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 2):
				{
					{
						NIM_BOOL T15_;
						tyProc_DyD4r9cv7AC5jKJQb1rPz0A T19_;
						T15_ = (NIM_BOOL)0;
						T15_ = eqStrings(key_q8si9a8j0iffMMe21H89aknQ, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_9));
						if (!(T15_)) goto LA16_;
						T15_ = eqStrings(val_C32W9cnRiWF3VO2YWSagqwQ, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_10));
						LA16_: ;
						if (!T15_) goto LA17_;
						memset((void*)(&T19_), 0, sizeof(T19_));
						T19_.ClP_0 = ((TM_V45tF8B8NBcxFcjfe7lhBw_11) (inputPosN_3tUdVKmL5NR9be6NvrCHtSg)); T19_.ClE_0 = NIM_NIL;
						asgnRef((void**) (&blackInput_ArmIfnivojEzI3b46HA6Vg.ClE_0), T19_.ClE_0);
						blackInput_ArmIfnivojEzI3b46HA6Vg.ClP_0 = T19_.ClP_0;
					}
					LA17_: ;
					{
						NIM_BOOL T22_;
						tyProc_DyD4r9cv7AC5jKJQb1rPz0A T26_;
						T22_ = (NIM_BOOL)0;
						T22_ = eqStrings(key_q8si9a8j0iffMMe21H89aknQ, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_9));
						if (!(T22_)) goto LA23_;
						T22_ = eqStrings(val_C32W9cnRiWF3VO2YWSagqwQ, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_12));
						LA23_: ;
						if (!T22_) goto LA24_;
						memset((void*)(&T26_), 0, sizeof(T26_));
						T26_.ClP_0 = ((TM_V45tF8B8NBcxFcjfe7lhBw_13) (choosePosN_FnR9a55ekWIcD5z7wNgKsmQ)); T26_.ClE_0 = NIM_NIL;
						asgnRef((void**) (&blackInput_ArmIfnivojEzI3b46HA6Vg.ClE_0), T26_.ClE_0);
						blackInput_ArmIfnivojEzI3b46HA6Vg.ClP_0 = T26_.ClP_0;
					}
					LA24_: ;
					{
						NIM_BOOL T29_;
						tyProc_DyD4r9cv7AC5jKJQb1rPz0A T33_;
						T29_ = (NIM_BOOL)0;
						T29_ = eqStrings(key_q8si9a8j0iffMMe21H89aknQ, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_14));
						if (!(T29_)) goto LA30_;
						T29_ = eqStrings(val_C32W9cnRiWF3VO2YWSagqwQ, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_10));
						LA30_: ;
						if (!T29_) goto LA31_;
						memset((void*)(&T33_), 0, sizeof(T33_));
						T33_.ClP_0 = ((TM_V45tF8B8NBcxFcjfe7lhBw_15) (inputPosN_3tUdVKmL5NR9be6NvrCHtSg)); T33_.ClE_0 = NIM_NIL;
						asgnRef((void**) (&whiteInput_48AJqfb5KCSIlBIaaWoCXg.ClE_0), T33_.ClE_0);
						whiteInput_48AJqfb5KCSIlBIaaWoCXg.ClP_0 = T33_.ClP_0;
					}
					LA31_: ;
					{
						NIM_BOOL T36_;
						tyProc_DyD4r9cv7AC5jKJQb1rPz0A T40_;
						T36_ = (NIM_BOOL)0;
						T36_ = eqStrings(key_q8si9a8j0iffMMe21H89aknQ, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_14));
						if (!(T36_)) goto LA37_;
						T36_ = eqStrings(val_C32W9cnRiWF3VO2YWSagqwQ, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_12));
						LA37_: ;
						if (!T36_) goto LA38_;
						memset((void*)(&T40_), 0, sizeof(T40_));
						T40_.ClP_0 = ((TM_V45tF8B8NBcxFcjfe7lhBw_16) (choosePosN_FnR9a55ekWIcD5z7wNgKsmQ)); T40_.ClE_0 = NIM_NIL;
						asgnRef((void**) (&whiteInput_48AJqfb5KCSIlBIaaWoCXg.ClE_0), T40_.ClE_0);
						whiteInput_48AJqfb5KCSIlBIaaWoCXg.ClP_0 = T40_.ClP_0;
					}
					LA38_: ;
				}
				break;
				case ((tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 3):
				{
					{
						NIM_BOOL T44_;
						tyProc_DyD4r9cv7AC5jKJQb1rPz0A T48_;
						T44_ = (NIM_BOOL)0;
						T44_ = eqStrings(key_q8si9a8j0iffMMe21H89aknQ, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_17));
						if (!(T44_)) goto LA45_;
						T44_ = eqStrings(val_C32W9cnRiWF3VO2YWSagqwQ, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_10));
						LA45_: ;
						if (!T44_) goto LA46_;
						memset((void*)(&T48_), 0, sizeof(T48_));
						T48_.ClP_0 = ((TM_V45tF8B8NBcxFcjfe7lhBw_18) (inputPosN_3tUdVKmL5NR9be6NvrCHtSg)); T48_.ClE_0 = NIM_NIL;
						asgnRef((void**) (&blackInput_ArmIfnivojEzI3b46HA6Vg.ClE_0), T48_.ClE_0);
						blackInput_ArmIfnivojEzI3b46HA6Vg.ClP_0 = T48_.ClP_0;
					}
					LA46_: ;
					{
						NIM_BOOL T51_;
						tyProc_DyD4r9cv7AC5jKJQb1rPz0A T55_;
						T51_ = (NIM_BOOL)0;
						T51_ = eqStrings(key_q8si9a8j0iffMMe21H89aknQ, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_17));
						if (!(T51_)) goto LA52_;
						T51_ = eqStrings(val_C32W9cnRiWF3VO2YWSagqwQ, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_12));
						LA52_: ;
						if (!T51_) goto LA53_;
						memset((void*)(&T55_), 0, sizeof(T55_));
						T55_.ClP_0 = ((TM_V45tF8B8NBcxFcjfe7lhBw_19) (choosePosN_FnR9a55ekWIcD5z7wNgKsmQ)); T55_.ClE_0 = NIM_NIL;
						asgnRef((void**) (&blackInput_ArmIfnivojEzI3b46HA6Vg.ClE_0), T55_.ClE_0);
						blackInput_ArmIfnivojEzI3b46HA6Vg.ClP_0 = T55_.ClP_0;
					}
					LA53_: ;
					{
						NIM_BOOL T58_;
						tyProc_DyD4r9cv7AC5jKJQb1rPz0A T62_;
						T58_ = (NIM_BOOL)0;
						T58_ = eqStrings(key_q8si9a8j0iffMMe21H89aknQ, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_20));
						if (!(T58_)) goto LA59_;
						T58_ = eqStrings(val_C32W9cnRiWF3VO2YWSagqwQ, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_10));
						LA59_: ;
						if (!T58_) goto LA60_;
						memset((void*)(&T62_), 0, sizeof(T62_));
						T62_.ClP_0 = ((TM_V45tF8B8NBcxFcjfe7lhBw_21) (inputPosN_3tUdVKmL5NR9be6NvrCHtSg)); T62_.ClE_0 = NIM_NIL;
						asgnRef((void**) (&whiteInput_48AJqfb5KCSIlBIaaWoCXg.ClE_0), T62_.ClE_0);
						whiteInput_48AJqfb5KCSIlBIaaWoCXg.ClP_0 = T62_.ClP_0;
					}
					LA60_: ;
					{
						NIM_BOOL T65_;
						tyProc_DyD4r9cv7AC5jKJQb1rPz0A T69_;
						T65_ = (NIM_BOOL)0;
						T65_ = eqStrings(key_q8si9a8j0iffMMe21H89aknQ, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_20));
						if (!(T65_)) goto LA66_;
						T65_ = eqStrings(val_C32W9cnRiWF3VO2YWSagqwQ, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_12));
						LA66_: ;
						if (!T65_) goto LA67_;
						memset((void*)(&T69_), 0, sizeof(T69_));
						T69_.ClP_0 = ((TM_V45tF8B8NBcxFcjfe7lhBw_22) (choosePosN_FnR9a55ekWIcD5z7wNgKsmQ)); T69_.ClE_0 = NIM_NIL;
						asgnRef((void**) (&whiteInput_48AJqfb5KCSIlBIaaWoCXg.ClE_0), T69_.ClE_0);
						whiteInput_48AJqfb5KCSIlBIaaWoCXg.ClP_0 = T69_.ClP_0;
					}
					LA67_: ;
				}
				break;
				case ((tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 1):
				case ((tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 0):
				{
				}
				break;
				}
			}
		} LA4: ;
	}
	gameStart_VGxPDTVR71IU5iZr1yJvqA(blackInput_ArmIfnivojEzI3b46HA6Vg, whiteInput_48AJqfb5KCSIlBIaaWoCXg);
}

NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void) {
static TNimNode* TM_V45tF8B8NBcxFcjfe7lhBw_2[2];
static TNimNode TM_V45tF8B8NBcxFcjfe7lhBw_0[4];
NTI_DyD4r9cv7AC5jKJQb1rPz0A_.size = sizeof(tyTuple_2uzTbg8jwom7zHhmM2RgHg);
NTI_DyD4r9cv7AC5jKJQb1rPz0A_.kind = 18;
NTI_DyD4r9cv7AC5jKJQb1rPz0A_.base = 0;
TM_V45tF8B8NBcxFcjfe7lhBw_2[0] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[1];
TM_V45tF8B8NBcxFcjfe7lhBw_0[1].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[1].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field0);
TM_V45tF8B8NBcxFcjfe7lhBw_0[1].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[1].name = "Field0";
TM_V45tF8B8NBcxFcjfe7lhBw_2[1] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[2];
NTI_sO5O0Qy9bzKs0atwA6HUBAw_.size = sizeof(tyObject_Env_maindotnim__sO5O0Qy9bzKs0atwA6HUBAw);
NTI_sO5O0Qy9bzKs0atwA6HUBAw_.kind = 17;
NTI_sO5O0Qy9bzKs0atwA6HUBAw_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_sO5O0Qy9bzKs0atwA6HUBAw_.flags = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[3].len = 0; TM_V45tF8B8NBcxFcjfe7lhBw_0[3].kind = 2;
NTI_sO5O0Qy9bzKs0atwA6HUBAw_.node = &TM_V45tF8B8NBcxFcjfe7lhBw_0[3];
NTI_58EFneeS9at7cA541QCoGAw_.size = sizeof(tyObject_Env_maindotnim__sO5O0Qy9bzKs0atwA6HUBAw*);
NTI_58EFneeS9at7cA541QCoGAw_.kind = 22;
NTI_58EFneeS9at7cA541QCoGAw_.base = (&NTI_sO5O0Qy9bzKs0atwA6HUBAw_);
NTI_58EFneeS9at7cA541QCoGAw_.marker = Marker_tyRef_58EFneeS9at7cA541QCoGAw;
TM_V45tF8B8NBcxFcjfe7lhBw_0[2].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[2].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field1);
TM_V45tF8B8NBcxFcjfe7lhBw_0[2].typ = (&NTI_58EFneeS9at7cA541QCoGAw_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[2].name = "Field1";
TM_V45tF8B8NBcxFcjfe7lhBw_0[0].len = 2; TM_V45tF8B8NBcxFcjfe7lhBw_0[0].kind = 2; TM_V45tF8B8NBcxFcjfe7lhBw_0[0].sons = &TM_V45tF8B8NBcxFcjfe7lhBw_2[0];
NTI_DyD4r9cv7AC5jKJQb1rPz0A_.node = &TM_V45tF8B8NBcxFcjfe7lhBw_0[0];
}

