/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/kaneko_takayuki/.choosenim/toolchains/nim-0.18.0/lib -o /Users/kaneko_takayuki/MyProgram/ReversiAI/src/nimcache/searchResult.o /Users/kaneko_takayuki/MyProgram/ReversiAI/src/nimcache/searchResult.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_SearchResultcolonObjectType__zAsotna64eELd4Sf5w32sA tyObject_SearchResultcolonObjectType__zAsotna64eELd4Sf5w32sA;
typedef struct RootObj RootObj;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_SearchResultcolonObjectType__zAsotna64eELd4Sf5w32sA {
  RootObj Sup;
NI value;
NI lastPosN;
};
static N_NIMCALL(void, Marker_tyRef_B9cTrhDFBURRqziYICNCAvA)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_zAsotna64eELd4Sf5w32sA_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_B9cTrhDFBURRqziYICNCAvA_;
static N_NIMCALL(void, Marker_tyRef_B9cTrhDFBURRqziYICNCAvA)(void* p, NI op) {
	tyObject_SearchResultcolonObjectType__zAsotna64eELd4Sf5w32sA* a;
	a = (tyObject_SearchResultcolonObjectType__zAsotna64eELd4Sf5w32sA*)p;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_SearchResultcolonObjectType__zAsotna64eELd4Sf5w32sA*, minus__Vty3RbFKjLQOgYqY9bvv5CQ)(tyObject_SearchResultcolonObjectType__zAsotna64eELd4Sf5w32sA* x) {
	tyObject_SearchResultcolonObjectType__zAsotna64eELd4Sf5w32sA* result;
	tyObject_SearchResultcolonObjectType__zAsotna64eELd4Sf5w32sA* T1_;
	result = (tyObject_SearchResultcolonObjectType__zAsotna64eELd4Sf5w32sA*)0;
	T1_ = (tyObject_SearchResultcolonObjectType__zAsotna64eELd4Sf5w32sA*)0;
	T1_ = (tyObject_SearchResultcolonObjectType__zAsotna64eELd4Sf5w32sA*) newObj((&NTI_B9cTrhDFBURRqziYICNCAvA_), sizeof(tyObject_SearchResultcolonObjectType__zAsotna64eELd4Sf5w32sA));
	(*T1_).Sup.m_type = (&NTI_zAsotna64eELd4Sf5w32sA_);
	(*T1_).value = ((NI64)-((*x).value));
	(*T1_).lastPosN = (*x).lastPosN;
	result = T1_;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, lt__0ZVrbyG0jTiHWR7uISrPNA)(tyObject_SearchResultcolonObjectType__zAsotna64eELd4Sf5w32sA* x, tyObject_SearchResultcolonObjectType__zAsotna64eELd4Sf5w32sA* y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((*x).value < (*y).value);
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_searchResultInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, unknown_searchResultDatInit000)(void) {
static TNimNode* TM_fPhyxVgwK7aQ3Ii4HVWfRQ_2[2];
static TNimNode TM_fPhyxVgwK7aQ3Ii4HVWfRQ_0[3];
NTI_zAsotna64eELd4Sf5w32sA_.size = sizeof(tyObject_SearchResultcolonObjectType__zAsotna64eELd4Sf5w32sA);
NTI_zAsotna64eELd4Sf5w32sA_.kind = 17;
NTI_zAsotna64eELd4Sf5w32sA_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_zAsotna64eELd4Sf5w32sA_.flags = 1;
TM_fPhyxVgwK7aQ3Ii4HVWfRQ_2[0] = &TM_fPhyxVgwK7aQ3Ii4HVWfRQ_0[1];
TM_fPhyxVgwK7aQ3Ii4HVWfRQ_0[1].kind = 1;
TM_fPhyxVgwK7aQ3Ii4HVWfRQ_0[1].offset = offsetof(tyObject_SearchResultcolonObjectType__zAsotna64eELd4Sf5w32sA, value);
TM_fPhyxVgwK7aQ3Ii4HVWfRQ_0[1].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_fPhyxVgwK7aQ3Ii4HVWfRQ_0[1].name = "value";
TM_fPhyxVgwK7aQ3Ii4HVWfRQ_2[1] = &TM_fPhyxVgwK7aQ3Ii4HVWfRQ_0[2];
TM_fPhyxVgwK7aQ3Ii4HVWfRQ_0[2].kind = 1;
TM_fPhyxVgwK7aQ3Ii4HVWfRQ_0[2].offset = offsetof(tyObject_SearchResultcolonObjectType__zAsotna64eELd4Sf5w32sA, lastPosN);
TM_fPhyxVgwK7aQ3Ii4HVWfRQ_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_fPhyxVgwK7aQ3Ii4HVWfRQ_0[2].name = "lastPosN";
TM_fPhyxVgwK7aQ3Ii4HVWfRQ_0[0].len = 2; TM_fPhyxVgwK7aQ3Ii4HVWfRQ_0[0].kind = 2; TM_fPhyxVgwK7aQ3Ii4HVWfRQ_0[0].sons = &TM_fPhyxVgwK7aQ3Ii4HVWfRQ_2[0];
NTI_zAsotna64eELd4Sf5w32sA_.node = &TM_fPhyxVgwK7aQ3Ii4HVWfRQ_0[0];
NTI_B9cTrhDFBURRqziYICNCAvA_.size = sizeof(tyObject_SearchResultcolonObjectType__zAsotna64eELd4Sf5w32sA*);
NTI_B9cTrhDFBURRqziYICNCAvA_.kind = 22;
NTI_B9cTrhDFBURRqziYICNCAvA_.base = (&NTI_zAsotna64eELd4Sf5w32sA_);
NTI_B9cTrhDFBURRqziYICNCAvA_.marker = Marker_tyRef_B9cTrhDFBURRqziYICNCAvA;
}

