/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/kaneko_takayuki/.choosenim/toolchains/nim-0.18.0/lib -o /Users/kaneko_takayuki/MyProgram/ReversiAI/src/nimcache/stdlib_parseopt2.o /Users/kaneko_takayuki/MyProgram/ReversiAI/src/nimcache/stdlib_parseopt2.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w;
typedef struct RootObj RootObj;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw;
struct tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w {
  RootObj Sup;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* cmd;
NI pos;
NimStringDesc* remainingShortOptions;
tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw kind;
NimStringDesc* key;
NimStringDesc* val;
};
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA {
NI a;
NI b;
};
typedef NIM_CHAR tyArray_1N75LKnZklmK4NsXtZ9bZiA[2];
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(void, initOptParser_sdCSBPv59coXTEz3qwUXMeA)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* cmdline, tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* Result);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__SRlIwYUUH1G46Yee9aMIFAQ)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* x, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* y);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, commandLineParams_WoBZMy8AVRATRE9bQuYWzCQ)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, at__s2ocO7QwvJg5hna9a9a004sw)(NimStringDesc** a, NI aLen_0);
static N_INLINE(NimStringDesc*, X5BX5D__xiaaX9b4cczHG39bivOynT9bgparseopt2)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qparseopt2)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix);
N_LIB_PRIVATE N_NIMCALL(void, nextOption_fUds30kiga89a9a6wuOFrkww)(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* p, NimStringDesc* token, NIM_BOOL allowEmpty);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_6e5MGL10HDAJ205lBYpWxw)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start, NI last);
N_LIB_PRIVATE N_NIMCALL(void, npo2next)(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* p);
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_w3uFmxpwEmgEXFUJjUl10w_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_n0GV8cT30u289bzvb9bOzCmw_;
STRING_LITERAL(TM_hJtUwp9bs9cZbgrKsWuACD3Q_6, "", 0);
STRING_LITERAL(TM_hJtUwp9bs9cZbgrKsWuACD3Q_7, "--", 2);
NIM_CONST tyArray_1N75LKnZklmK4NsXtZ9bZiA TM_hJtUwp9bs9cZbgrKsWuACD3Q_8 = {58,
61}
;
STRING_LITERAL(TM_hJtUwp9bs9cZbgrKsWuACD3Q_9, "-", 1);

N_LIB_PRIVATE N_NIMCALL(void, initOptParser_sdCSBPv59coXTEz3qwUXMeA)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* cmdline, tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* Result) {
{	genericReset((void*)Result, (&NTI_w3uFmxpwEmgEXFUJjUl10w_));
	(*Result).Sup.m_type = (&NTI_w3uFmxpwEmgEXFUJjUl10w_);
	unsureAsgnRef((void**) (&(*Result).remainingShortOptions), copyString(((NimStringDesc*) &TM_hJtUwp9bs9cZbgrKsWuACD3Q_6)));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = eqeq__SRlIwYUUH1G46Yee9aMIFAQ(cmdline, NIM_NIL);
		if (!T3_) goto LA4_;
		unsureAsgnRef((void**) (&(*Result).cmd), commandLineParams_WoBZMy8AVRATRE9bQuYWzCQ());
		goto BeforeRet_;
	}
	LA4_: ;
	unsureAsgnRef((void**) (&(*Result).cmd), at__s2ocO7QwvJg5hna9a9a004sw(cmdline->data, cmdline->Sup.len));
	}BeforeRet_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, initOptParser_7ywjeToZhKr9cLpneviH7zg)(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* Result) {
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T1_;
{	genericReset((void*)Result, (&NTI_w3uFmxpwEmgEXFUJjUl10w_));
	(*Result).Sup.m_type = (&NTI_w3uFmxpwEmgEXFUJjUl10w_);
	T1_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	T1_ = commandLineParams_WoBZMy8AVRATRE9bQuYWzCQ();
	initOptParser_sdCSBPv59coXTEz3qwUXMeA(T1_, Result);
	goto BeforeRet_;
	}BeforeRet_: ;
}

static N_INLINE(NimStringDesc*, X5BX5D__xiaaX9b4cczHG39bivOynT9bgparseopt2)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x) {
	NimStringDesc* result;
	NI a;
	NI L;
	result = (NimStringDesc*)0;
	a = x.a;
	L = (NI)((NI)(x.b - a) + ((NI) 1));
	result = mnewString(((NI) (L)));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < L)) goto LA3;
				i = i_2;
				result->data[i] = s->data[(NI)(i + a)];
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}

static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qparseopt2)(NI a, NI b) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA result;
	memset((void*)(&result), 0, sizeof(result));
	result.a = a;
	result.b = b;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, nextOption_fUds30kiga89a9a6wuOFrkww)(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* p, NimStringDesc* token, NIM_BOOL allowEmpty) {
{	{
		NIM_CHAR splitchar;
		NI i;
		splitchar = (NIM_CHAR)0;
		i = ((NI) 0);
		{
			if (!(((NI) (i)) <= ((NI) 1))) goto LA4_;
			{
				while (1) {
					splitchar = TM_hJtUwp9bs9cZbgrKsWuACD3Q_8[(i)- 0];
					{
						NIM_BOOL T10_;
						NI pos;
						tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T13_;
						tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T14_;
						T10_ = (NIM_BOOL)0;
						T10_ = contains_6e5MGL10HDAJ205lBYpWxw(token, splitchar);
						if (!T10_) goto LA11_;
						pos = nsuFindChar(token, splitchar, ((NI) 0), ((NI) 0));
						T13_ = dotdot__vDQySKWzgnxQdUarow6k5Qparseopt2(((NI) 0), (NI)(pos - ((NI) 1)));
						unsureAsgnRef((void**) (&(*p).key), X5BX5D__xiaaX9b4cczHG39bivOynT9bgparseopt2(token, T13_));
						T14_ = dotdot__vDQySKWzgnxQdUarow6k5Qparseopt2((NI)(pos + ((NI) 1)), (NI)((token ? token->Sup.len : 0) - ((NI) 1)));
						unsureAsgnRef((void**) (&(*p).val), X5BX5D__xiaaX9b4cczHG39bivOynT9bgparseopt2(token, T14_));
						goto BeforeRet_;
					}
					LA11_: ;
					{
						if (!(((NI) 1) <= ((NI) (i)))) goto LA17_;
						goto LA6;
					}
					LA17_: ;
					i += ((NI) 1);
				}
			} LA6: ;
		}
		LA4_: ;
	}
	unsureAsgnRef((void**) (&(*p).key), copyString(token));
	{
		if (!allowEmpty) goto LA21_;
		unsureAsgnRef((void**) (&(*p).val), copyString(((NimStringDesc*) &TM_hJtUwp9bs9cZbgrKsWuACD3Q_6)));
	}
	goto LA19_;
	LA21_: ;
	{
		tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T24_;
		T24_ = dotdot__vDQySKWzgnxQdUarow6k5Qparseopt2(((NI) 0), (NI)((token ? token->Sup.len : 0) - ((NI) 1)));
		unsureAsgnRef((void**) (&(*p).remainingShortOptions), X5BX5D__xiaaX9b4cczHG39bivOynT9bgparseopt2(token, T24_));
		npo2next(p);
	}
	LA19_: ;
	}BeforeRet_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, npo2next)(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* p) {
	NimStringDesc* token;
{	{
		tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T5_;
		tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T6_;
		if (!!((((*p).remainingShortOptions ? (*p).remainingShortOptions->Sup.len : 0) == ((NI) 0)))) goto LA3_;
		(*p).kind = ((tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 3);
		T5_ = dotdot__vDQySKWzgnxQdUarow6k5Qparseopt2(((NI) 0), ((NI) 0));
		unsureAsgnRef((void**) (&(*p).key), X5BX5D__xiaaX9b4cczHG39bivOynT9bgparseopt2((*p).remainingShortOptions, T5_));
		unsureAsgnRef((void**) (&(*p).val), copyString(((NimStringDesc*) &TM_hJtUwp9bs9cZbgrKsWuACD3Q_6)));
		T6_ = dotdot__vDQySKWzgnxQdUarow6k5Qparseopt2(((NI) 1), (NI)(((*p).remainingShortOptions ? (*p).remainingShortOptions->Sup.len : 0) - ((NI) 1)));
		unsureAsgnRef((void**) (&(*p).remainingShortOptions), X5BX5D__xiaaX9b4cczHG39bivOynT9bgparseopt2((*p).remainingShortOptions, T6_));
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NI T9_;
		T9_ = ((*p).cmd ? (*p).cmd->Sup.len : 0);
		if (!(T9_ <= (*p).pos)) goto LA10_;
		(*p).kind = ((tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 0);
		goto BeforeRet_;
	}
	LA10_: ;
	token = (*p).cmd->data[(*p).pos];
	(*p).pos += ((NI) 1);
	{
		NIM_BOOL T14_;
		tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T17_;
		NimStringDesc* T18_;
		T14_ = (NIM_BOOL)0;
		T14_ = nsuStartsWith(token, ((NimStringDesc*) &TM_hJtUwp9bs9cZbgrKsWuACD3Q_7));
		if (!T14_) goto LA15_;
		(*p).kind = ((tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 2);
		T17_ = dotdot__vDQySKWzgnxQdUarow6k5Qparseopt2(((NI) 2), (NI)((token ? token->Sup.len : 0) - ((NI) 1)));
		T18_ = (NimStringDesc*)0;
		T18_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgparseopt2(token, T17_);
		nextOption_fUds30kiga89a9a6wuOFrkww(p, T18_, NIM_TRUE);
	}
	goto LA12_;
	LA15_: ;
	{
		NIM_BOOL T20_;
		tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T23_;
		NimStringDesc* T24_;
		T20_ = (NIM_BOOL)0;
		T20_ = nsuStartsWith(token, ((NimStringDesc*) &TM_hJtUwp9bs9cZbgrKsWuACD3Q_9));
		if (!T20_) goto LA21_;
		(*p).kind = ((tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 3);
		T23_ = dotdot__vDQySKWzgnxQdUarow6k5Qparseopt2(((NI) 1), (NI)((token ? token->Sup.len : 0) - ((NI) 1)));
		T24_ = (NimStringDesc*)0;
		T24_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgparseopt2(token, T23_);
		nextOption_fUds30kiga89a9a6wuOFrkww(p, T24_, NIM_TRUE);
	}
	goto LA12_;
	LA21_: ;
	{
		(*p).kind = ((tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 1);
		unsureAsgnRef((void**) (&(*p).key), copyString(token));
		unsureAsgnRef((void**) (&(*p).val), copyString(((NimStringDesc*) &TM_hJtUwp9bs9cZbgrKsWuACD3Q_6)));
	}
	LA12_: ;
	}BeforeRet_: ;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_parseopt2Init000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_parseopt2DatInit000)(void) {
static TNimNode* TM_hJtUwp9bs9cZbgrKsWuACD3Q_2[6];
static TNimNode* TM_hJtUwp9bs9cZbgrKsWuACD3Q_3[4];
NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_5;
static char* NIM_CONST TM_hJtUwp9bs9cZbgrKsWuACD3Q_4[4] = {
"cmdEnd", 
"cmdArgument", 
"cmdLongOption", 
"cmdShortOption"};
static TNimNode TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[12];
NTI_w3uFmxpwEmgEXFUJjUl10w_.size = sizeof(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w);
NTI_w3uFmxpwEmgEXFUJjUl10w_.kind = 17;
NTI_w3uFmxpwEmgEXFUJjUl10w_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_2[0] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[1];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[1].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[1].offset = offsetof(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w, cmd);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[1].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[1].name = "cmd";
TM_hJtUwp9bs9cZbgrKsWuACD3Q_2[1] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[2];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[2].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[2].offset = offsetof(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w, pos);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[2].name = "pos";
TM_hJtUwp9bs9cZbgrKsWuACD3Q_2[2] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[3];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[3].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[3].offset = offsetof(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w, remainingShortOptions);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[3].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[3].name = "remainingShortOptions";
TM_hJtUwp9bs9cZbgrKsWuACD3Q_2[3] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[4];
NTI_n0GV8cT30u289bzvb9bOzCmw_.size = sizeof(tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw);
NTI_n0GV8cT30u289bzvb9bOzCmw_.kind = 14;
NTI_n0GV8cT30u289bzvb9bOzCmw_.base = 0;
NTI_n0GV8cT30u289bzvb9bOzCmw_.flags = 3;
for (TM_hJtUwp9bs9cZbgrKsWuACD3Q_5 = 0; TM_hJtUwp9bs9cZbgrKsWuACD3Q_5 < 4; TM_hJtUwp9bs9cZbgrKsWuACD3Q_5++) {
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[TM_hJtUwp9bs9cZbgrKsWuACD3Q_5+5].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[TM_hJtUwp9bs9cZbgrKsWuACD3Q_5+5].offset = TM_hJtUwp9bs9cZbgrKsWuACD3Q_5;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[TM_hJtUwp9bs9cZbgrKsWuACD3Q_5+5].name = TM_hJtUwp9bs9cZbgrKsWuACD3Q_4[TM_hJtUwp9bs9cZbgrKsWuACD3Q_5];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_3[TM_hJtUwp9bs9cZbgrKsWuACD3Q_5] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[TM_hJtUwp9bs9cZbgrKsWuACD3Q_5+5];
}
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[9].len = 4; TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[9].kind = 2; TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[9].sons = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_3[0];
NTI_n0GV8cT30u289bzvb9bOzCmw_.node = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[9];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[4].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[4].offset = offsetof(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w, kind);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[4].typ = (&NTI_n0GV8cT30u289bzvb9bOzCmw_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[4].name = "kind";
TM_hJtUwp9bs9cZbgrKsWuACD3Q_2[4] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[10];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[10].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[10].offset = offsetof(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w, key);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[10].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[10].name = "key";
TM_hJtUwp9bs9cZbgrKsWuACD3Q_2[5] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[11];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[11].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[11].offset = offsetof(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w, val);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[11].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[11].name = "val";
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[0].len = 6; TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[0].kind = 2; TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[0].sons = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_2[0];
NTI_w3uFmxpwEmgEXFUJjUl10w_.node = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[0];
}

